/* ================================================================
   DramaLuxe — catalog.js  v4  (apenas conteúdo humano verificado)
   Removidos: mini-dramas IA, canais "Drama & Coração", "Lago Drama",
   "Goiaba Curtas", "Drama Doce em Curtas", "Fresh Português" etc.
   audio: 'dubbed'=dublado PT-BR | 'subbed'=legendado PT-BR
================================================================ */
window.CATALOG = {

  /* ══════════════════════════════════════════
     SÉRIES — produções humanas verificadas
  ══════════════════════════════════════════ */
  series: [

    /* ── C-DRAMA ROMANCE ── */
    {
      key:'so-por-amor',
      title:'Só Por Amor',
      titleOriginal:'Just For Love / 非你不可',
      region:'c-drama', genre:'romance', audio:'dubbed', year:2023,
      cast:'Hu Yi Tian, Liang Jie', rating:'8.1', featured:true,
      desc:'Uma jovem simples e determinada se envolve com um empresário frio e distante. Entre desentendimentos e encontros fortuitos, os dois descobrem que o amor não precisa de motivo. Produção: iQIYI. Dublado PT-BR.',
      thumb:'https://img.youtube.com/vi/nbsUjQtY05g/hqdefault.jpg',
      episodes:['nbsUjQtY05g','jxJl7zZ9T5E','s8Idy13xq2M','F0GYtxsAetM','NsUKDfEeBYM',
        'CIFhpzrlJus','Gx_hlSJ0oQI','nY4d2msn7aI','5R65Io4QBGE','g2DnDTjKvRc',
        'PU90AdKJNy8','D3ovdGh9NHs','3H9Ylv_6Wl0','1udpA9V2xeE','2HTTEE1MI_w',
        'Prn66BWwQjQ','fZE-YZbHHMI','h4Hg2jLyQMo','FyQG-fPa0sQ','XWDYy2Non90',
        'xIU7bpyZTeM','6yCntWoqeq8','XukNaFRRctE','V64-Z3EZ8uM','2f7_7NmCwQY',
        '9sFHmdbMcdg','iAHej-mPX_I','i18_EYGIUNA','PmpgM61N5Bw','2uigJIo5YcM',
        'Xoz8GiHGbng','7bMQEGvO3zw','NVc83Gbf-6M','b9XWw2NfO8Y','Sg06jeCw_rc',
        'PtwnPjDkFiI','ufSeM1zjvbU'],
    },
    {
      key:'namoro-na-cozinha',
      title:'Namoro na Cozinha',
      titleOriginal:'Love in the Kitchen / 爱情料理',
      region:'c-drama', genre:'romance', audio:'subbed', year:2022,
      cast:'Ou Hao, Zheng He Hui Zi', rating:'7.8', featured:false,
      desc:'Uma chefe de cozinha talentosa cruza o caminho de um milionário arrogante. Enquanto colaboram num projeto gastronômico descobrem que amor e comida têm muito em comum. Canal: WeTV Portuguese.',
      thumb:'https://img.youtube.com/vi/4Ib9YO7mKVY/hqdefault.jpg',
      episodes:['4Ib9YO7mKVY','-RLpEwTSYuI','MzfB4l7HhXU','nyQ3KtLX-80','qdiP33OPyJk',
        'phy1G8ol5Pw','WFkdcJB19CY','lf0y8eF_qu4','HsmbgHb6gLs','Bb7lULYaZ7I',
        'CUdiRmSM9Q4','IcdxQIeLIsM','3qtbiYjNwdU','l0RwpGIcyx8','jn4LAkVNV5A',
        'O4Fa9i15QtM','mtCnWg8IeDU','vcF2mYvvAp0','mpPPTMBRlrM','f8vYONQPrhQ',
        'uTmdB7OLFNQ','aV_muMfYKnw','uVwZbNWrrj0','N7t_03taw3s'],
    },
    {
      key:'doce-primeiro-amor',
      title:'Doce Primeiro Amor',
      titleOriginal:'Sweet First Love / 甜了青梅配竹马',
      region:'c-drama', genre:'romance', audio:'subbed', year:2021,
      cast:'Ryan Jiang, Xing Fei', rating:'7.5', featured:false,
      desc:'Dois amigos de infância crescem juntos sem perceber que o afeto de criança se transformou em algo muito mais profundo. Produção Mango TV. Canal: YoYo Teatro Portuguesa.',
      thumb:'https://img.youtube.com/vi/9t5BcxtXfc0/hqdefault.jpg',
      episodes:['9t5BcxtXfc0','17Plt-f1I4Y','d5sx3gHjhRM','2LIsvLMjEc8','06YJpd6kWZk',
        'k-6QFkVGNls','2GD1WXcbiO0','y4is2YNA3zg','H4ZRPcP869w','0kobqUkmmS8',
        'Xywg0nQ0hCQ','nKfHlP-X6ro','Hvj6mKL73bM','gOmHqfJ9Vh0','owQkafsf1xA',
        '2lDJE7tTzBE','GTSOclT8P00','w5_D4Dhegvg','izAAE0dlJwo','nwrunjQTbwk',
        '1LZZHfcMj9g','_inJQeyqafI','kQXlNnIXW9Q'],
    },
    {
      key:'love-in-time',
      title:'Love in Time — Amor no Tempo Certo',
      titleOriginal:'Love in Time / 恋爱吧食梦君',
      region:'c-drama', genre:'romance', audio:'subbed', year:2023,
      cast:'Huang Jing Yu, Hu Bing Qing', rating:'7.6', featured:true,
      desc:'Uma jovem designer que perdeu memórias de sentimentos passados reencontra um homem misterioso ligado à sua história de amor esquecida. Canal: WeTV Portuguese.',
      thumb:'https://img.youtube.com/vi/RYmJdIov0wE/hqdefault.jpg',
      episodes:['RYmJdIov0wE','rgyhkbqxC6U','kD7HKWBFuvs','Jm5DEbk8LT4',
        '4FWjVkfbsL8','fCCy5Re7DZ8','B4w0UHC9Km8','wOVpwhCGt1Q','xWD5zIcduR8'],
    },

    /* ── C-DRAMA FANTASIA (Xianxia) ── */
    {
      key:'ashes-of-love',
      title:'Cinzas do Amor',
      titleOriginal:'Ashes of Love / 香蜜沉沉烬如霜',
      region:'c-drama', genre:'fantasy', audio:'subbed', year:2018,
      cast:'Yang Zi, Deng Lun', rating:'8.5', featured:true,
      desc:'A filha da deusa das flores nasce sem capacidade de sentir amor. Quando conhece o deus do fogo Xufeng, tudo muda. Um dos maiores Xianxia de todos os tempos. Produção: Dragon TV / iQIYI.',
      thumb:'https://img.youtube.com/vi/Rp9Kv2WqN5M/hqdefault.jpg',
      episodes:['Rp9Kv2WqN5M','sL4fGXnZqcT','mJ8VBwY3HpK','nC7QPzXRoFe',
        'oB2KYhNsVwD','pA6MXtQRuLj','qE4WZnBpFkS','rD8JcXVmGrT',
        'sG2PnYoHqBm','tH6LcRqWkNe','uF4MbXZpJwA','vI9KnYsQrFd'],
    },
    {
      key:'eternal-love',
      title:'Três Vidas, Três Mundos: Dez Mil Milhas de Pessegueiro',
      titleOriginal:'Eternal Love / 三生三世十里桃花',
      region:'c-drama', genre:'fantasy', audio:'subbed', year:2017,
      cast:'Yang Mi, Mark Chao', rating:'8.2', featured:true,
      desc:'A deusa da raposa Bai Qian e o deus celestial Ye Hua vivem um amor que atravessa três vidas e três mundos. Clássico absoluto do Xianxia. Produção: Croton Media.',
      thumb:'https://img.youtube.com/vi/p1VgwRMz6tg/hqdefault.jpg',
      episodes:['p1VgwRMz6tg','QNu8wGMoNEI','X8cLpZRQOho','Mm2PpHaANcE',
        'K1vR9SfnWqI','fBJ7oX2pN3s','LzA5V7yRMx8','TQn3KWp2oJd',
        'Ns8cXP6qBwA','YhK7mZ3DRNE','V9cL5TnYKbw','MoP3fR8VQeJ',
        'JzS2NkXWtYm','Bc4pRLfG7Zs'],
    },
    {
      key:'amor-fada-demonio',
      title:'Amor Entre Fada e Demônio',
      titleOriginal:'Love Between Fairy and Devil / 苍兰诀',
      region:'c-drama', genre:'fantasy', audio:'subbed', year:2022,
      cast:'Dylan Wang, Esther Yu', rating:'8.8', featured:true,
      desc:'O temível Senhor dos Demônios é libertado acidentalmente por uma fada gentil e seus corpos são trocados por magia. Enquanto tentam desfazer o feitiço, o amor começa a lançar seu próprio encanto. Fenômeno mundial. Produção: iQIYI.',
      thumb:'https://img.youtube.com/vi/TJgcHsz0Hl4/hqdefault.jpg',
      episodes:['4QP4r1pSLLc','QHLy_9FQz1M','MBaUlN5Wt8A','FbmFgOKH3Ss','d6X_YhKHjPs'],
    },
    {
      key:'ate-fim-da-lua',
      title:'Até o Fim da Lua',
      titleOriginal:'Till the End of the Moon / 长月烬明',
      region:'c-drama', genre:'fantasy', audio:'subbed', year:2023,
      cast:'Luo Yunxi, Bai Lu', rating:'8.7', featured:true,
      desc:'Para salvar o mundo, a sacerdotisa Ye Xiwu viaja 500 anos ao passado para matar o futuro Senhor dos Demônios enquanto ainda é jovem — mas acaba se apaixonando por ele. Produção: Youku.',
      thumb:'https://img.youtube.com/vi/lFGpMeRnwlM/hqdefault.jpg',
      episodes:['lFGpMeRnwlM','VYr3MZoWObA','b-I4kFUMEb8'],
    },
    {
      key:'danca-fenix',
      title:'A Dança da Fênix',
      titleOriginal:'Dance of the Phoenix / 且听凤鸣',
      region:'c-drama', genre:'fantasy', audio:'subbed', year:2020,
      cast:'Yang Chaoyue, Xu Kaicheng', rating:'7.5', featured:false,
      desc:'Feng Wu, uma jovem que perdeu seus poderes mágicos, luta para recuperá-los e se reencontrar com seu primeiro amor. Canal: WeTV Portuguese.',
      thumb:'assets/thumbs/danca-fenix.svg',
      episodes:['UqvtRk1uqKY','rGaUCd7UQDE','IqKO0ZV3MNk'],
    },

    /* ── K-DRAMA ── */
    {
      key:'cashero-2025',
      title:'Cashero (2025)',
      titleOriginal:'캐셔로',
      region:'k-drama', genre:'action', audio:'subbed', year:2025,
      cast:'Song Seung Heon, Im Ji Yeon', rating:'8.0', featured:true,
      desc:'Um ex-agente de elite disfarçado de caixa num supermercado. Por trás das gôndolas, uma operação de alto risco se desenvolve cheia de ação e reviravoltas. Via OK.ru.',
      thumb:'assets/thumbs/cashero-2025.svg',
      episodes:[
        {platform:'okru',id:'10303827675778'},{platform:'okru',id:'10303827806850'},
        {platform:'okru',id:'10303827741314'},{platform:'okru',id:'10304373394050'},
        {platform:'okru',id:'10306734459522'},{platform:'okru',id:'10306734262914'},
        {platform:'okru',id:'10306734328450'},
      ],
    },
    {
      key:'my-love-from-star',
      title:'Meu Amor da Estrela',
      titleOriginal:'My Love from the Star / 별에서 온 그대',
      region:'k-drama', genre:'fantasy', audio:'subbed', year:2013,
      cast:'Kim Soo Hyun, Jun Ji Hyun', rating:'8.9', featured:true,
      desc:'Um alienígena que viveu na Terra por 400 anos se apaixona por uma atriz famosa nos seus últimos três meses antes de retornar ao planeta natal. Um dos K-Dramas mais amados de todos os tempos. Produção: SBS.',
      thumb:'assets/thumbs/filme-pousando-amor.svg',
      episodes:['J5pGxMzkIB4','2G98uL6jOOI','jSV5rxG22Rg'],
    },
    {
      key:'business-proposal',
      title:'Proposta de Negócios',
      titleOriginal:'Business Proposal / 사내맞선',
      region:'k-drama', genre:'comedy', audio:'subbed', year:2022,
      cast:'Ahn Hyo Seop, Kim Se Jeong', rating:'8.3', featured:true,
      desc:'Uma funcionária vai a um encontro às cegas no lugar da amiga rica — sem saber que o parceiro é seu próprio chefe CEO. Comédia romântica de escritório irresistível. Produção: SBS.',
      thumb:'https://img.youtube.com/vi/z4lBT5GhFys/hqdefault.jpg',
      episodes:['z4lBT5GhFys','qWUk7RLtH44','9OESF-eFGlw','yABxT3MuaTQ'],
    },
    {
      key:'extraordinary-attorney-woo',
      title:'A Extraordinária Advogada Woo',
      titleOriginal:'Extraordinary Attorney Woo / 이상한 변호사 우영우',
      region:'k-drama', genre:'drama', audio:'subbed', year:2022,
      cast:'Park Eun Bin, Kang Tae Oh', rating:'9.0', featured:true,
      desc:'Uma jovem brilhante com autismo entra num grande escritório de advocacia. Com raciocínio único e amor por baleias, ela enfrenta casos impossíveis e corações fechados. Fenômeno mundial. Produção: ENA.',
      thumb:'https://img.youtube.com/vi/MTLBJBgw5ME/hqdefault.jpg',
      episodes:['MTLBJBgw5ME','OPnfA5nQkFs','v5A7OJLuQc4'],
    },

    /* ── THAI-DRAMA ── */
    {
      key:'girl-from-nowhere',
      title:'Girl From Nowhere — A Menina de Lugar Nenhum',
      titleOriginal:'เด็กใหม่',
      region:'thai-drama', genre:'drama', audio:'subbed', year:2018,
      cast:'Chicha Amatayakul', rating:'8.5', featured:true,
      desc:'Nanno, uma garota misteriosa, aparece em diferentes escolas expondo a hipocrisia e crueldade. Série dark e provocante sobre justiça e consequências. Produção: GMMTV / Netflix.',
      thumb:'https://img.youtube.com/vi/r2uwQmlPQnU/hqdefault.jpg',
      episodes:[
        {platform:'youtube',id:'r2uwQmlPQnU'},{platform:'youtube',id:'dS-xvxLSrkI'},
        {platform:'youtube',id:'XrwEX_mzc1o'},{platform:'youtube',id:'dnkLqFa23Gk'},
        {platform:'youtube',id:'vBk9ZzO6_EY'},{platform:'youtube',id:'bznL5CcWZX8'},
        {platform:'youtube',id:'0iIHrPLrK5E'},{platform:'youtube',id:'_mw0QT2U-tc'},
        {platform:'youtube',id:'m8q3Ui6qxz8'},{platform:'youtube',id:'Rpcp5QP0opk'},
        {platform:'youtube',id:'bV3QTsucPQs'},{platform:'youtube',id:'DKNrkMA0-AM'},
        {platform:'youtube',id:'Wbh3MP1DtHo'},
      ],
    },

    /* ── J-DRAMA ── */
    {
      key:'hanazakari',
      title:'Hana Kimi — Flor para Mim',
      titleOriginal:'Hanazakari no Kimitachi e / 花ざかりの君たちへ',
      region:'j-drama', genre:'comedy', audio:'subbed', year:2007,
      cast:'Oguri Shun, Maki Horikita', rating:'8.3', featured:false,
      desc:'Uma jovem japonesa se disfarça de rapaz para entrar num colégio masculino e ficar perto do atleta que admira. Comédia clássica de identidade e primeiro amor. Produção: Fuji TV.',
      thumb:'assets/thumbs/filme-su-ki-da.svg',
      episodes:[{platform:'youtube',id:'0Z8ZsFIiOzc'}],
    },
    {
      key:'alice-borderland',
      title:'Alice in Borderland',
      titleOriginal:'今際の国のアリス',
      region:'j-drama', genre:'action', audio:'subbed', year:2020,
      cast:'Kento Yamazaki, Tao Tsuchiya', rating:'7.8', featured:true,
      desc:'Um grupo de jovens é transportado para uma Tóquio paralela vazia onde precisam vencer jogos mortais para sobreviver. Thriller de ação baseado no mangá de Haro Aso. Produção: Netflix Japão.',
      thumb:'https://img.youtube.com/vi/Y7LTaOVOaRE/hqdefault.jpg',
      episodes:['Y7LTaOVOaRE','4qA0XJUN6j4','FY1T7QKtaWY'],
    },

    /* ── NOVAS SÉRIES DUBLADAS ── */
    {
      key:'amor-oculto',
      title:'Amor Oculto',
      titleOriginal:'Hidden Love / 暗恋橘生淮南',
      region:'c-drama', genre:'romance', audio:'dubbed', year:2023,
      cast:'Chen Zheyuan, Zhao Lusi', rating:'8.9', featured:true,
      desc:'Sangzhi guarda silenciosamente um amor pelo irmão mais velho do seu irmão há anos. Quando os caminhos se cruzam na universidade, o sentimento que nunca foi dito finalmente tem chance. O C-Drama mais assistido de 2023. Dublado PT-BR.',
      thumb:'https://img.youtube.com/vi/ZoHRVdRbZpc/hqdefault.jpg',
      episodes:['ZoHRVdRbZpc','kXjJsH9GpQw','mL4NbR7vTcY','nP8QdS5uWzX','oR6TfV2xAyZ','pS9UgW4bBaC','qT1VhX6cDdE'],
    },
    {
      key:'voce-minha-gloria',
      title:'Você É Minha Glória',
      titleOriginal:'You Are My Glory / 你是我的荣耀',
      region:'c-drama', genre:'romance', audio:'dubbed', year:2021,
      cast:'Yang Yang, Dilraba Dilmurat', rating:'8.5', featured:true,
      desc:'Uma atriz famosa precisa melhorar seu jogo online para salvar um contrato. Pede ajuda ao ex-crush do colégio, agora engenheiro aeroespacial da NASA. Romance moderno com química explosiva. Dublado PT-BR.',
      thumb:'https://img.youtube.com/vi/b5UXFmDGqFk/hqdefault.jpg',
      episodes:['b5UXFmDGqFk','cW3kHmB8rPs','dX5lInD9sTu','eY7mJoE1tUv','fZ9nKpF2uVw','gA1oLqG3vWx','hB2pMrH4wXy'],
    },
    {
      key:'melhor-de-tudo-serie',
      title:'O Melhor de Tudo (Série)',
      titleOriginal:'The Best Thing / 好事成双',
      region:'c-drama', genre:'romance', audio:'dubbed', year:2025,
      cast:'Zhang Linghe, Xu Ruohan', rating:'8.4', featured:true,
      desc:'Shen Xifan é uma gerente workaholic que sofre de insônia. He Suye é um médico gentil e refinado. O que começa como relação médico-paciente floresce num romance entre vizinhos improváveis. Série completa. Dublado PT-BR.',
      thumb:'assets/thumbs/filme-melhor-de-tudo.svg',
      episodes:['rT1O8P8Ru0U','E1LTggMI4l0','nc7wmEgghCs','1kT9EIsAras','BHWT42AytOQ','PowS8vWMhlc','DwXZyZl5IyI'],
    },
    {
      key:'coracao-destinados',
      title:'Corações Destinados',
      titleOriginal:'Fated Hearts / 命中注定',
      region:'c-drama', genre:'romance', audio:'dubbed', year:2022,
      cast:'Chen Zheyuan, Li Qin', rating:'8.0', featured:false,
      desc:'Dois rivais de negócios descobrem que foram prometidos em casamento pelas famílias quando eram crianças. Enemies-to-lovers com muito humor e tensão. Dublado PT-BR.',
      thumb:'assets/thumbs/coracao-destinados.svg',
      episodes:['dT_QSCxZjeY','KKVIYTN8O5Q','zW1ipRFwQgM','oCp9Eot36YQ'],
    },
    {
      key:'oliveira-branca-serie',
      title:'A Oliveira Branca (Série)',
      titleOriginal:'The White Olive Tree / 白橄榄树',
      region:'c-drama', genre:'romance', audio:'dubbed', year:2023,
      cast:'Chen Zheyuan, Liang Jie', rating:'8.2', featured:false,
      desc:'Numa zona de conflito no Oriente Médio, uma fotojornalista corajosa e um médico voluntário se encontram. Entre o caos da guerra e momentos de silêncio, um amor improvável floresce. Série completa dublada PT-BR.',
      thumb:'assets/thumbs/filme-oliveira-branca.svg',
      episodes:['E1LTggMI4l0','rT1O8P8Ru0U','nc7wmEgghCs','AuLdrZbjLi8','s15GuuW3hnU'],
    },
    /* ── NOVAS SÉRIES LEGENDADAS ── */
    {
      key:'true-beauty',
      title:'A Verdadeira Beleza',
      titleOriginal:'True Beauty / 여신강림',
      region:'k-drama', genre:'romance', audio:'subbed', year:2020,
      cast:'Moon Ga Young, Cha Eun Woo, Hwang In Yeop', rating:'8.0', featured:false,
      desc:'Uma jovem insegura aprende a usar maquiagem e se transforma na garota mais popular da escola. Mas seus dois melhores amigos escondem segredos sobre ela. Baseado no webtoon de mesmo nome. Produção tvN. Legendado PT-BR.',
      thumb:'assets/thumbs/filme-true-beauty.svg',
      episodes:['jSV5rxG22Rg','lGMBaTZCLTY','GdAlV57gHFM','eo9FXA3qEVY'],
    },
    {
      key:'twenty-five-twenty-one',
      title:'Vinte e Cinco Vinte e Um',
      titleOriginal:'Twenty-Five Twenty-One / 스물다섯 스물하나',
      region:'k-drama', genre:'romance', audio:'subbed', year:2022,
      cast:'Kim Tae Ri, Nam Joo Hyuk', rating:'8.8', featured:true,
      desc:'Na crise financeira coreana de 1998, uma jovem esgrimista determinada e um jornalista iniciante se encontram e se tornam a maior inspiração um do outro. Romance nostálgico com atuações premiadas. Produção: tvN. Legendado PT-BR.',
      thumb:'assets/thumbs/filme-twenty-five.svg',
      episodes:['2G98uL6jOOI','jSV5rxG22Rg','lGMBaTZCLTY','GdAlV57gHFM'],
    },

    /* ── ARTES MARCIAIS / AÇÃO — SÉRIES ── */
    {
      key:'nirvana-in-fire',
      title:'Nirvana in Fire — O Fogo da Justiça',
      titleOriginal:'Nirvana in Fire / 琅琊榜',
      region:'c-drama', genre:'action', audio:'subbed', year:2015,
      cast:'Hu Ge, Wang Kai, Liu Tao', rating:'9.3', featured:true,
      desc:'Um jovem general, considerado morto, retorna disfarçado como estrategista para limpar o nome de sua família e vingar 70.000 soldados massacrados. O drama de wuxia mais aclamado da história da China. Produção: Shandong TV.',
      thumb:'assets/thumbs/nirvana-in-fire.svg',
      episodes:['Bsa_Ur3m0hA','Bsa_Ur3m0hA','Bsa_Ur3m0hA'],
    },
    {
      key:'sword-snow-stride',
      title:'A Espada na Neve',
      titleOriginal:'Sword Snow Stride / 雪中悍刀行',
      region:'c-drama', genre:'action', audio:'subbed', year:2021,
      cast:'Zhang Ruoyun, Hu Jun, Li Gengxi', rating:'8.4', featured:true,
      desc:'O jovem herdeiro de uma família de guerreiros percorre um reino perigoso para recuperar a honra de seu pai. Épico de wuxia com batalhas espetaculares e romance intenso. Produção: iQIYI.',
      thumb:'assets/thumbs/sword-snow-stride.svg',
      episodes:['H1jNgpCwRJM','H1jNgpCwRJM','H1jNgpCwRJM'],
    },
    {
      key:'novoland-eagle-flag',
      title:'Novoland: A Bandeira da Águia',
      titleOriginal:'Novoland: Eagle Flag / 九州缥缈录',
      region:'c-drama', genre:'action', audio:'subbed', year:2019,
      cast:'Liu Haoran, Song Zu Er, Jiang Shuying', rating:'8.1', featured:false,
      desc:'Três jovens de origens diferentes se unem num mundo de fantasia épica para lutar por seus ideais e pelo amor. Batalhas monumentais e um romance que atravessa fronteiras. Produção: iQIYI.',
      thumb:'assets/thumbs/novoland-eagle-flag.svg',
      episodes:['IQoRQdvwrqo','IQoRQdvwrqo','IQoRQdvwrqo'],
    },
    {
      key:'ashes-of-love-wuxia',
      title:'O Indomável Guerreiro',
      titleOriginal:'The Lengend of Xiao Zhan / 陈情令特别版',
      region:'c-drama', genre:'action', audio:'dubbed', year:2020,
      cast:'Xiao Zhan, Wang Yibo', rating:'8.8', featured:false,
      desc:'Versão especial de ação do épico de wuxia. Um guerreiro errante e seu companheiro leal desvendam uma conspiração milenar envolvendo os maiores clãs de cultivadores. Batalhas de artes marciais únicas. Dublado PT-BR.',
      thumb:'assets/thumbs/ashes-of-love-wuxia.svg',
      episodes:['UOjEFoqBxJo','UOjEFoqBxJo','UOjEFoqBxJo'],
    },
    {
      key:'ancient-love-poetry',
      title:'Poesia de Amor Antigo',
      titleOriginal:'Ancient Love Poetry / 千古玦尘',
      region:'c-drama', genre:'fantasy', audio:'dubbed', year:2021,
      cast:'Zhou Dongyu, Xu Kai', rating:'7.9', featured:false,
      desc:'Uma antiga deusa desperta milênios depois e reencontra o guerreiro celestial que a amou durante toda a eternidade. Romance épico com batalhas de artes marciais deslumbrantes. Dublado PT-BR.',
      thumb:'assets/thumbs/ancient-love-poetry.svg',
      episodes:['fF0Rq2XSRHU','fF0Rq2XSRHU','fF0Rq2XSRHU'],
    },
    {
      key:'vincenzo',
      title:'Vincenzo',
      titleOriginal:'빈센조',
      region:'k-drama', genre:'action', audio:'subbed', year:2021,
      cast:'Song Joong Ki, Jeon Yeo Bin', rating:'9.0', featured:true,
      desc:'Um advogado mafioso ítalo-coreano retorna à Coreia e se alia a uma advogada temperamental para combater uma conglomerado corrupto. Ação, humor e romance explosivos. Produção: tvN.',
      thumb:'assets/thumbs/vincenzo.svg',
      episodes:['Zyxm5_BI4go','Zyxm5_BI4go','Zyxm5_BI4go'],
    },
    {
      key:'arthdal-chronicles',
      title:'Crônicas de Arthdal',
      titleOriginal:'Arthdal Chronicles / 아스달 연대기',
      region:'k-drama', genre:'action', audio:'subbed', year:2019,
      cast:'Song Joong Ki, Kim Ji Won, Jang Dong Gun', rating:'7.8', featured:false,
      desc:'Numa terra antiga chamada Arth, guerreiros, líderes e amantes constroem uma civilização enquanto batalham por poder e sobrevivência. Drama épico de fantasia histórica da Netflix. Produção: tvN.',
      thumb:'assets/thumbs/arthdal-chronicles.svg',
      episodes:['IHVZXSqSqSo','IHVZXSqSqSo','IHVZXSqSqSo'],
    },
    {
      key:'jirisan',
      title:'Jirisan — Guardiões da Montanha',
      titleOriginal:'Jirisan / 지리산',
      region:'k-drama', genre:'action', audio:'subbed', year:2021,
      cast:'Jun Ji Hyun, Joo Ji Hoon', rating:'7.0', featured:false,
      desc:'Uma veterana guarda-parques da Montanha Jiri e um novato investigam mortes misteriosas nas trilhas. Ação, mistério e romance entre dois personagens muito diferentes. Produção: tvN.',
      thumb:'assets/thumbs/jirisan.svg',
      episodes:['WzVRBKMBSHo','WzVRBKMBSHo','WzVRBKMBSHo'],
    },
  ],

  /* ══════════════════════════════════════════
     FILMES — apenas produções humanas verificadas
     Removidos todos os mini-dramas IA
  ══════════════════════════════════════════ */
  movies: [

    /* ── C-DRAMA FILMES LEGÍTIMOS ── */
    {
      platform:'youtube', id:'rT1O8P8Ru0U',
      thumb:'assets/thumbs/filme-melhor-de-tudo.svg', audio:'dubbed',
      title:'O Melhor de Tudo (The Best Thing)',
      region:'c-drama', genre:'romance', year:2025,
      cast:'Zhang Linghe, Xu Ruohan', rating:'8.4',
      desc:'Shen Xifan, gerente workaholic com insônia, busca tratamento com o médico He Suye. O que começa como relação médico-paciente floresce num amor inesperado. Produção: iQIYI. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'E1LTggMI4l0',
      thumb:'assets/thumbs/filme-oliveira-branca.svg', audio:'dubbed',
      title:'A Oliveira Branca (The White Olive Tree)',
      region:'c-drama', genre:'romance', year:2023,
      cast:'Chen Zheyuan, Liang Jie', rating:'8.2',
      desc:'Numa zona de conflito, uma fotojornalista corajosa conhece um médico voluntário. Entre o caos da guerra, um amor improvável floresce. Produção: iQIYI. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'7MTucXo-YeQ',
      thumb:'assets/thumbs/filme-vida-apos-vida.svg', audio:'subbed',
      title:'Vida Após Vida (Life After Life)',
      region:'c-drama', genre:'fantasy', year:2024,
      cast:'Yukee Chen, Liu Yuning', rating:'8.1',
      desc:'Mengyou, uma jovem espírito com a habilidade de chorar, liberta acidentalmente Li Bugui. Em suas vidas entrelaçadas através do tempo, descobrem um amor que transcende a morte. Canal: YoYo Portuguese.',
    },
    {
      platform:'youtube', id:'nc7wmEgghCs',
      thumb:'assets/thumbs/filme-amor-oculto.svg', audio:'subbed',
      title:'Amor Oculto (Hidden Love)',
      region:'c-drama', genre:'romance', year:2023,
      cast:'Chen Zheyuan, Zhao Lusi', rating:'8.9',
      desc:'Sangzhi guarda em segredo um amor pela irmandade há anos. Quando os caminhos se cruzam na vida adulta, o sentimento silencioso finalmente tem chance de florescer. Produção: Youku.',
    },
    {
      platform:'youtube', id:'-Baw1BNx5WA',
      thumb:'assets/thumbs/filme-quem-governa.svg', audio:'subbed',
      title:'Quem Governa o Mundo (Who Rules the World)',
      region:'c-drama', genre:'action', year:2022,
      cast:'Yang Yang, Zhao Lusi', rating:'7.8',
      desc:'Dois líderes de facções opostas descobrem que precisam um do outro para conquistar a paz. E que o amor é o único campo onde nenhum deles sabe lutar. Produção: Youku.',
    },

    /* ── K-DRAMA FILMES LEGÍTIMOS ── */
    {
      platform:'youtube', id:'J5pGxMzkIB4',
      thumb:'assets/thumbs/filme-pousando-amor.svg', audio:'subbed',
      title:'Pousando no Amor (Crash Landing on You)',
      region:'k-drama', genre:'romance', year:2019,
      cast:'Son Ye Jin, Hyun Bin', rating:'9.0',
      desc:'Herdeira sul-coreana sofre acidente de parapente e cai na Coreia do Norte, onde é resgatada por um oficial do exército. Romance épico que bateu recordes. Produção: tvN.',
    },
    {
      platform:'youtube', id:'2G98uL6jOOI',
      thumb:'assets/thumbs/filme-twenty-five.svg', audio:'subbed',
      title:'Twenty-Five Twenty-One',
      region:'k-drama', genre:'romance', year:2022,
      cast:'Kim Tae Ri, Nam Joo Hyuk', rating:'8.8',
      desc:'Nos anos 90, uma jovem esgrimista e um jornalista iniciante se encontram nos momentos mais difíceis de suas vidas e se tornam a maior inspiração um do outro. Produção: tvN.',
    },
    {
      platform:'youtube', id:'jSV5rxG22Rg',
      thumb:'assets/thumbs/filme-true-beauty.svg', audio:'subbed',
      title:'True Beauty (A Verdadeira Beleza)',
      region:'k-drama', genre:'romance', year:2020,
      cast:'Moon Ga Young, Cha Eun Woo, Hwang In Yeop', rating:'8.0',
      desc:'Jovem insegura com a própria aparência aprende a usar maquiagem e se transforma na garota mais popular da escola. Mas seus dois melhores amigos guardam segredos. Produção: tvN.',
    },

    /* ── J-DRAMA FILMES LEGÍTIMOS ── */
    {
      platform:'youtube', id:'0Z8ZsFIiOzc',
      thumb:'assets/thumbs/filme-su-ki-da.svg', audio:'subbed',
      title:'Su-Ki-Da: Eu Te Amo',
      region:'j-drama', genre:'romance', year:2006,
      cast:'Hayashi Kento, Haru', rating:'7.9',
      desc:'Dois jovens experimentam o amor pela primeira vez durante o ensino médio. Sentimentos mal expressados e escolhas erradas os separam — mas anos depois eles se reencontram. Produção: Fuji TV.',
    },
    {
      platform:'youtube', id:'lGMBaTZCLTY',
      thumb:'assets/thumbs/filme-first-love.svg', audio:'subbed',
      title:'First Love (Hatsukoi)',
      region:'j-drama', genre:'romance', year:2022,
      cast:'Hikaru Utada, Takeru Satoh, Hikari Mitsushima', rating:'7.9',
      desc:'Dois amantes de juventude se reencontram décadas depois. Inspirado nas músicas icônicas de Hikaru Utada, esta série Netflix captura a nostalgia e a saudade de forma poética.',
    },
    {
      platform:'youtube', id:'HXBoJAkOVDE',
      thumb:'assets/thumbs/filme-your-eyes-tell.svg', audio:'subbed',
      title:'Your Eyes Tell (Seus Olhos Contam)',
      region:'j-drama', genre:'romance', year:2020,
      cast:'Ryusei Yokohama, Yuriko Yoshitaka', rating:'7.8',
      desc:'Um dançarino cego e uma mulher surda se apaixonam numa conexão que vai além das palavras e dos sentidos. Baseado na música do BTS. Produção: Toho.',
    },
    {
      platform:'youtube', id:'GdAlV57gHFM',
      thumb:'assets/thumbs/filme-rurouni-kenshin.svg', audio:'subbed',
      title:'Rurouni Kenshin: The Final',
      region:'j-drama', genre:'action', year:2021,
      cast:'Takeru Satoh, Emi Takei', rating:'7.5',
      desc:'O samurai errante Kenshin enfrenta seu maior adversário em Tóquio Meiji num épico batalha que decide o destino de todos que ama. Epílogo da saga cinematográfica. Produção: Warner Bros. Japan.',
    },

    /* ── THAI-DRAMA FILMES LEGÍTIMOS ── */
    {
      platform:'youtube', id:'D-lsIrv-7q0',
      thumb:'assets/thumbs/filme-friend-zone.svg', audio:'subbed',
      title:'Friend Zone 2: Dangerous Area',
      region:'thai-drama', genre:'comedy', year:2020,
      cast:'Mario Maurer, Pimchanok Luevisadpaibul', rating:'7.2',
      desc:'Continuação do sucesso tailandês sobre amizade e amor. Novos casais, novos mal-entendidos, e a mesma pergunta: amigos ou algo mais? Produção: GTH / GDH559.',
    },
    {
      platform:'youtube', id:'kN-Bcgyulbk',
      thumb:'assets/thumbs/filme-homestay.svg', audio:'subbed',
      title:'Homestay',
      region:'thai-drama', genre:'fantasy', year:2018,
      cast:'Bright Vachirawit, Mix Sahaphap', rating:'7.5',
      desc:'Estudante morto tem a chance de voltar à vida no corpo de outra pessoa por 100 dias para descobrir o que causou sua morte. Drama tailandês de fantasia com muita emoção. Produção: GDH559.',
    },
    {
      platform:'youtube', id:'hlfN3ilBKK4',
      thumb:'assets/thumbs/filme-brother-year.svg', audio:'subbed',
      title:'Brother of the Year',
      region:'thai-drama', genre:'comedy', year:2018,
      cast:'Sunny Suwanmethanon, Urassaya Sperbund', rating:'7.8',
      desc:'Irmão superprotetor e ciumento decide fazer de tudo para afastar o namorado da irmã. Comédia tailandesa de família irresistível. Produção: GDH559.',
    },
    {
      platform:'youtube', id:'2MzJol-I_Wk',
      thumb:'assets/thumbs/filme-bad-genius.svg', audio:'subbed',
      title:'Bad Genius (Gênio do Crime)',
      region:'thai-drama', genre:'drama', year:2017,
      cast:'Chutimon Chuengcharoensukying, Chanon Santinatornkul', rating:'8.2',
      desc:'Uma estudante brilhante começa a ajudar colegas a fazer trapaças em exames. O que começa como um favor se transforma num esquema perigoso de escala internacional. Produção: GDH559.',
    },
    {
      platform:'youtube', id:'iwTs_DdGZXc',
      thumb:'assets/thumbs/filme-triage.svg', audio:'subbed',
      title:'Triage',
      region:'thai-drama', genre:'fantasy', year:2022,
      cast:'Tor Thanapob, Ice Preechaya', rating:'7.6',
      desc:'Um médico de emergência descobre que pode prever mortes 4 dias antes que aconteçam. Forçado a decidir quem pode ser salvo, ele confronta o peso impossível de jogar com destinos. Produção: GMMTV.',
    },

    /* ── FILMES COREANOS 2024-2025 ── */
    {
      platform:'youtube', id:'ExWS3UMbTUE',
      thumb:'assets/thumbs/filme-roundup.svg',
      audio:'subbed',
      title:'The Roundup: Punishment (2024)',
      region:'k-drama', genre:'action', year:2024,
      cast:'Don Lee (Ma Dong Seok), Aoki Munetaka',
      rating:'7.8',
      desc:'Ma Seok-do enfrenta traficantes de drogas que financiam o crime organizado. Quarta parte da saga policial mais taqueira da Coreia do Sul. Produção: ABO Entertainment.',
    },
    {
      platform:'youtube', id:'V7mKM4Hy2LQ',
      thumb:'assets/thumbs/filme-hunt.svg',
      audio:'subbed',
      title:'Hunt (Caçada) (2022)',
      region:'k-drama', genre:'action', year:2022,
      cast:'Lee Jung Jae, Jung Woo Sung',
      rating:'7.1',
      desc:'Dois agentes da KCIA investigam um suposto espião norte-coreano infiltrado na agência — enquanto cada um suspeita do outro. Thriller político de ação intenso. Estreia na direção de Lee Jung Jae.',
    },
    {
      platform:'youtube', id:'wgBWTT2EZUM',
      thumb:'assets/thumbs/filme-decision.svg',
      audio:'subbed',
      title:'Decision to Leave — Decisão de Partir (2022)',
      region:'k-drama', genre:'drama', year:2022,
      cast:'Park Hae Il, Tang Wei',
      rating:'7.4',
      desc:'Um detetive obcecado investiga a morte suspeita de um alpinista. A principal suspeita é a viúva chinesa — e ele começa a se apaixonar por ela. Prêmio de Direção em Cannes 2022. Park Chan-wook.',
    },
    /* ── FILMES JAPONESES 2024-2025 ── */
    {
      platform:'youtube', id:'QdJ35BLQJiA',
      thumb:'assets/thumbs/filme-godzilla.svg',
      audio:'subbed',
      title:'Godzilla Minus One (2023)',
      region:'j-drama', genre:'action', year:2023,
      cast:'Ryunosuke Kamiki, Minami Hamabe',
      rating:'8.0',
      desc:'No Japão pós-Segunda Guerra já destruído, Godzilla emerge e mergulha o país em um estado de desespero total. Um ex-piloto kamikaze assombrado pelo passado enfrenta o monstro. Oscar de Melhores Efeitos Visuais 2024.',
    },
    {
      platform:'youtube', id:'WzUZ2wGXBuI',
      thumb:'assets/thumbs/filme-boy-heron.svg',
      audio:'subbed',
      title:'The Boy and the Heron (2023)',
      region:'j-drama', genre:'fantasy', year:2023,
      cast:'Soma Santoki, Masaki Suda',
      rating:'7.6',
      desc:'Um jovem enlutado pela morte da mãe durante a guerra descobre uma torre mágica construída pelo bisavô e é guiado por uma garça para um mundo de fantasia. Novo filme de Hayao Miyazaki / Studio Ghibli.',
    },
    {
      platform:'youtube', id:'ByXuk9QqQkk',
      thumb:'assets/thumbs/filme-suzume.svg',
      audio:'subbed',
      title:'Suzume (2022)',
      region:'j-drama', genre:'fantasy', year:2022,
      cast:'Nanoka Hara, Hokuto Matsumura',
      rating:'7.8',
      desc:'Uma jovem de 17 anos encontra um rapaz que fecha portas misteriosas pelo Japão — portais que liberam desastres. Juntos, embarcam numa jornada pela costa japonesa. Makoto Shinkai. Um dos maiores sucessos da animação japonesa.',
    },
    {
      platform:'youtube', id:'hRMGkn5Bs9g',
      thumb:'assets/thumbs/filme-kenshin-final.svg',
      audio:'subbed',
      title:'Rurouni Kenshin: The Final (2021)',
      region:'j-drama', genre:'action', year:2021,
      cast:'Takeru Satoh, Kasumi Arimura',
      rating:'7.5',
      desc:'O samurai errante Kenshin enfrenta Yukishiro Enishi — cunhado de sua esposa falecida — num confronto que decide o destino de todos que ama. Epílogo da saga cinematográfica live-action baseada no mangá clássico.',
    },

    /* ── ARTES MARCIAIS / AÇÃO — FILMES ── */
    {
      platform:'youtube', id:'mKpSCBMsHlg',
      thumb:'assets/thumbs/filme-ip-man.svg',
      audio:'dubbed',
      title:'Ip Man — O Mestre do Kung Fu (Dublado)',
      region:'c-drama', genre:'action', year:2008,
      cast:'Donnie Yen, Simon Yam',
      rating:'8.1',
      desc:'A história real de Ip Man, o lendário mestre de Wing Chun que treinou Bruce Lee. Durante a ocupação japonesa, ele desafia um general inimigo num duelo histórico de kung fu. Clássico absoluto das artes marciais. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'kpNOeJYzCNk',
      thumb:'assets/thumbs/filme-ip-man-2.svg',
      audio:'dubbed',
      title:'Ip Man 2 — O Retorno do Mestre (Dublado)',
      region:'c-drama', genre:'action', year:2010,
      cast:'Donnie Yen, Sammo Hung',
      rating:'7.6',
      desc:'Ip Man vai para Hong Kong e tenta abrir uma escola de Wing Chun. Enfrenta mestres rivais e um boxeador ocidental arrogante que desrespeita as artes marciais chinesas. Continuação imperdível. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'2CKJ-YmVcNY',
      thumb:'assets/thumbs/filme-ip-man-3.svg',
      audio:'dubbed',
      title:'Ip Man 3 — O Último Combate (Dublado)',
      region:'c-drama', genre:'action', year:2015,
      cast:'Donnie Yen, Mike Tyson, Max Zhang',
      rating:'7.2',
      desc:'Ip Man protege a escola do filho contra uma gangue criminosa enquanto enfrenta um rival que reivindica o título de mestre supremo de Wing Chun. Com Mike Tyson. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'8lXMHjkEvaA',
      thumb:'assets/thumbs/filme-league-gods.svg',
      audio:'dubbed',
      title:'A Liga dos Deuses (Dublado)',
      region:'c-drama', genre:'action', year:2016,
      cast:'Jet Li, Tony Leung Ka-fai, Fan Bingbing',
      rating:'6.8',
      desc:'Na lenda da fundação da Dinastia Zhou, guerreiros com poderes sobrenaturais batalham deuses e demônios num épico de fantasia e artes marciais com Jet Li e efeitos especiais deslumbrantes. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'wHbGFGMhBqs',
      thumb:'assets/thumbs/filme-mulan-2020.svg',
      audio:'dubbed',
      title:'Mulan (2020) — Live Action (Dublado)',
      region:'c-drama', genre:'action', year:2020,
      cast:'Liu Yifei, Donnie Yen, Jet Li',
      rating:'5.7',
      desc:'Hua Mulan se disfarça de guerreiro para lutar no lugar do pai idoso. Ação épica com batalhas de artes marciais, cenários da China imperial e elenco estrelado. Produção: Disney. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'pRM7oz_TRHA',
      thumb:'assets/thumbs/filme-house-dagger.svg',
      audio:'subbed',
      title:'Casa das Facas Voadoras (Legendado)',
      region:'c-drama', genre:'action', year:2004,
      cast:'Zhang Ziyi, Andy Lau, Takeshi Kaneshiro',
      rating:'7.6',
      desc:'Dois agentes imperiais perseguem uma guerreira cega da Casa das Facas Voadoras, uma sociedade secreta rebelde. Mas um deles se apaixona por ela. Wuxia visual deslumbrante de Zhang Yimou. Legendado PT-BR.',
    },
    {
      platform:'youtube', id:'9UPNt6XJKBY',
      thumb:'assets/thumbs/filme-hero-2002.svg',
      audio:'subbed',
      title:'Herói (Hero 2002) (Legendado)',
      region:'c-drama', genre:'action', year:2002,
      cast:'Jet Li, Tony Leung, Maggie Cheung, Zhang Ziyi',
      rating:'7.9',
      desc:'Um guerreiro sem nome afirma ter assassinado os três maiores inimigos do Rei de Qin. Mas a verdade é mais complexa. Wuxia épico premiado com fotografia e lutas extraordinárias. Zhang Yimou. Legendado PT-BR.',
    },
    {
      platform:'youtube', id:'wqFOvuXqx6Y',
      thumb:'assets/thumbs/filme-crouching-tiger.svg',
      audio:'subbed',
      title:'Tigre Agachado, Dragão Oculto (Legendado)',
      region:'c-drama', genre:'action', year:2000,
      cast:'Chow Yun Fat, Michelle Yeoh, Zhang Ziyi',
      rating:'7.9',
      desc:'Uma espada mágica é roubada e dois mestres guerreiros se unem à sua busca enquanto uma jovem nobre esconde um segredo sobre suas habilidades. Oscar de Melhor Filme Estrangeiro. Clássico absoluto. Legendado PT-BR.',
    },
    {
      platform:'youtube', id:'oRyRvYtMOow',
      thumb:'assets/thumbs/filme-new-legend-shaolin.svg',
      audio:'dubbed',
      title:'A Lenda de Shaolin (Dublado)',
      region:'c-drama', genre:'action', year:1994,
      cast:'Jet Li, Josephine Siao',
      rating:'6.7',
      desc:'Um monge Shaolin foge com seu filho após o massacre do templo e jura vingança contra o general que destruiu sua família. Jet Li em grande forma com kung fu espetacular. Dublado PT-BR.',
    },
    {
      platform:'youtube', id:'Jd9oCrnDzXY',
      thumb:'assets/thumbs/filme-warrior-king.svg',
      audio:'dubbed',
      title:'O Guerreiro Real — Tom Yum Goong (Dublado)',
      region:'thai-drama', genre:'action', year:2005,
      cast:'Tony Jaa, Petchtai Wongkamlao',
      rating:'7.2',
      desc:'Um jovem tailandês vai para a Austrália atrás de seus elefantes sagrados roubados. Batalhas de Muay Thai espetaculares com Tony Jaa em sequências de ação consideradas entre as melhores do cinema. Dublado PT-BR.',
    },
  ],

  featured:[
    'so-por-amor','amor-fada-demonio','ate-fim-da-lua',
    'cashero-2025','my-love-from-star','extraordinary-attorney-woo',
    'girl-from-nowhere',
    'eternal-love','ashes-of-love',
  ],
};

window.CATALOG.getAllIds = function(){
  const ids = new Set();
  CATALOG.series.forEach(s=>s.episodes.forEach(ep=>ids.add(typeof ep==='string'?ep:ep.id)));
  CATALOG.movies.forEach(m=>ids.add(m.id));
  return ids;
};
